### ISSUE TITLE
Allgemeine Sachen

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-arthistory#12]
Das Feld `langid={<SPRACHE>}` regelt in welcher Sprache der Eintrag in der Bibliographie erfolgt. Dies wirkt sich auf Trennungsregeln, Anführungszeichen und Bibstrings (bspw. `vols.` anstatt `Bde.`; `pp.` anstatt `S.`).
Möchte man angeben in welcher Sprache das Werk verfasst wurde, dann das Feld `language = {<SPRACHE>}` wählen, @AlfonsoMuskedunder

**Comment by AlfonsoMuskedunder** [comment]
Darf ich mal interessehalber eine Frage zu `arthistory.cbx` stellen?  `source` wird ja als Option definiert, wenn ich es richtig verstehe. Heißt das, dass für den `source`-Fall eine `shorthand` erstellt werden wird?

**Comment by LukasCBossert** [comment]
ich bin mir noch nicht ganz sicher, wie ich es gestalte. Vielleicht braucht man `source` gar nicht, indem man einfach die `shorthand` definiert. Sobald das Feld `shorthand` ausgefüllt ist, wird es automatisch für die Fußnote genommen.

**Comment by LukasCBossert** [comment]
ich habe in der PDF (5. Aufl. Seite 59-61) nochmals geschaut: Das Vollzitat ändert sich für eine Quelle nicht, es ist nur die Zitationsweise in der Fußnote; daher ist `options={source}` unnötig, es reicht `shorthand = {NAME, TITEL}` mit `keywords = {source}`, damit man später ein eigenes Quellenverzeichnis machen kann.

**Comment by AlfonsoMuskedunder** [comment]
Und bei bei `catalog` "lohnt" es sich, eine Fallunterscheidung in die `.cbx`-Datei einzubauen, weil man ohnehin einen Dokumenttyp mit neuen Feldern definiert und so die Zitation auf relativ leichte Weise vollständig "automatisieren" kann?

**Comment by LukasCBossert** [comment]
Genau. Ich weiß noch nicht, wie man für Bestandskataloge das machen kann. Aber soweit ich sehe, unterscheiden die sich im Vollzitat auch nicht, sodass am Besten die Fußnotenzitation über eine `shorthand` gemacht werden kann.

**Comment by LukasCBossert** [comment]
Ich denke nun, dass man für man für Bestandskataloge

- neuen Eintragstyp (bspw. @catalog, wenn man für Ausstellungskatalog @exhibcatalog wählt)

oder

- dies über `option={catalog}` ansteuert und man es als @book behandelt.

In beiden Fällen spart man sich das manuelle Ausfüllen einer `shorthand`. 

Ggf. würde ich zur ersten Variante tendieren, dann wird analog zwischen Ausstellungskatalog und Bestandskatalog unterschieden.
Deine Meinung @AlfonsoMuskedunder ?

**Comment by AlfonsoMuskedunder** [comment]
Das Umgehen der `shorthand` ist ohnehin schon mal super!

Bzgl. der zwei Optionen habe ich ehrlich gesagt keine feste Meinung. Die Frage ist, welche Kriterien man anlegen möchte?
- Einerseits ist streng genommen die jeweils eine Katalogart der anderen ja nicht untergeordnet, was aus meiner Sicht für getrennte Typen spräche (ohne dass ich mich jemals mit Prinzipien der Bibliographie beschäftigt hätte)
- Andererseits sagt H., dass sie in ihrem gesamten Studium nur äußerst selten mit Bestandskatalogen zu tun gehabt hat (sie kann sich spontan an kein Bsp. erinnern), was vielleicht für die Behandlung als Ausnahme spräche
Ach, ich denke ich stimme mit dir überein; mein Gefühl sagt mir auch, die Typenunterscheidung wäre vielleicht die sauberere Sache. (Das Ganze unter der Voraussetzung, dass der Programmieraufwand ähnlich wäre!)

**Comment by LukasCBossert** [comment]
ich denke auch, dass es besser ist die zwei katalogtypen über eintragstypen zu unterscheiden.
auch wenn es praktisch kaum vorkommt, würde ich aufnehmen, um den leitfaden abzuarbeiten.

ich habe das repo öffentlich gemacht, um moewe besser einbinden zu können, da ich die sortierung und die option 'firstcitefull' noch nicht hinbekomme.

**Comment by AlfonsoMuskedunder** [comment]
Nur interessehalber: Woran hapert es bei der Sortierung? In deinem "dirty hack" hatte das ja schon funktioniert.

**Comment by LukasCBossert** [comment]
Genau; da hat es funktioniert, was daran lag, dass ich `shorthand` dafür missbraucht habe und bei der Sortierung eingestellt, dass zuerst die `shorthand` berücksichtigt werden soll. 
Aktuell ist `Ausst.-Kat.` ein sog. `bibstring` (um es in anderen Sprachen auch definieren zu können), das heißt aber, dass ich die Sortierung dazubringen muss bei `@catalog`, `@exhibcatalog` den `bibstring` zu berücksichtigen. Aktuell werden `@catalog` und `@exhibcatalog` über ihren `editor` einsortiert.
