### ISSUE TITLE
@catalog (Bestandskatalog)

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-arthistory#14]
Mir scheint hier eine gewisse Inkonsequenz in den Vorgaben zu sein:
<img width="1189" alt="bildschirmfoto 2016-10-04 um 12 14 25" src="https://cloud.githubusercontent.com/assets/12896078/19071564/107cc42e-8a31-11e6-8daa-45a43c8b0ec8.png">

Es geht um `Kat. Frankfurt 2010`: Dies ist der dritte Band des Gesamtwerks (`Holländische Gemälde im Städel..`) und hat somit einen eigenen Bibliographieeintrag.

Auf der rechten Seite (Seite 53) wird die Möglichkeit genannt, alle Bände zu zitieren, wobei man dann in den Fußnote explizit angeben muss, welchen Band man zitiert. 
Dies scheint mir unnötig zu sein, da man ja jeden Band eigen zitieren kann.

**Comment by AlfonsoMuskedunder** [comment]
Ich finde die 5. Auflage eher schlechter als die 4., in diesem konkreten Falle zumindest was die Präsentation betrifft. (Schon die Tatsache, dass die Zitationen im Leitfaden selbst in einem anderen Stil gesetzt ist als jener, den man beschreibt!, siehe z.B. Kapitälchen.)

Trotzdem finde ich es in dem vorliegenden Fall grundsätzlich richtig, einem Verfasser beide Möglichkeiten an die Hand zu geben. Es sind ja Fälle denkbar, in denen man aus welchen Gründen auch immer einerseits auf das Gesamtwerk verweisen möchte, und später im Text auf eine bestimmte Stelle. Dann wäre es komisch, in der Bibliographie sowohl die gesamte Ausgabe sowie darunter einen Teilband aufzuführen, oder irre ich mich.

**Comment by LukasCBossert** [comment]
An sich hast du schon recht. Aber auf das Gesamtwerk in der Fußnote zunächst zu verweisen und dann doch explizit auf einen Band (mit eigenem Titel, Hrsg. etc.) finde ich einfach umständlich. Aber das kann jeder so machen, wie er/sie will - in der Programmierung ändert das nichts.
