### ISSUE TITLE
"Dritter Zusatz", siehe S. 48 - wie verfahren?

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#16]
![dritterzusatz](https://cloud.githubusercontent.com/assets/10466043/19095478/106262f4-8a96-11e6-8f09-b85020baa2eb.png)
Nach einem etwaigen Untertitel kann es noch einen dritten Zusatz geben, mit einem Semikolon als separator. Siehe z.B. die beiden Festschriften Corsepius2004 und Tjarks2007. Ich habe das Semikolon jetzt jeweils händisch in den Untertitel aufgenommen. Sollte man anders verfahren?

**Comment by LukasCBossert** [comment]
das habe ich eigentlich schon gemacht, ist es nicht sichtbar.? trifft auf die felder titleaddon zu.

--- gesendet von unterwegs ---

**Comment by AlfonsoMuskedunder** [comment]
My bad! Nächstes Mal suche ich das pdf mit der Literaturangabe nach dem entsprechenden Zeichen ab und vergleiche einen etwaigen Treffer mit der bib-Datei.

**Comment by LukasCBossert** [comment]
kein problem. lieber etwas zuviel anmerken, als zu wenig.

--- gesendet von unterwegs ---
