### ISSUE TITLE
Bei References erscheint der publisher vor dem title

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#18]
Siehe Beispiel "AllgemeinesKunstlerlexikon".

**Comment by LukasCBossert** [comment]
ist das falsch?

siehe 5. Auflage Seite 58

<img width="795" alt="bildschirmfoto 2016-10-05 um 13 15 43" src="https://cloud.githubusercontent.com/assets/12896078/19111081/f15db102-8afd-11e6-878a-6c171bb845cc.png">
![bildschirmfoto 2016-10-05 um 13 15 55](https://cloud.githubusercontent.com/assets/12896078/19111080/f15cf384-8afd-11e6-833a-72259e0749eb.png)

**Comment by AlfonsoMuskedunder** [comment]
Du hast natürlich Recht, sorry. Ich hab natürlich wieder in mein Heft der 4. Auflage geschaut. Tut mir leid, ich sollte erst immer beide Auflagen checken, bevor ich hier ein issue absondere...

Allerdings führen die beiden Beispiele darunter (5. Auflage) den Verlagsnamen ja nicht. Wir denken, dass dem Leitfadenverfasser ein Fehler unterlaufen ist und der Verlagsname generell nicht aufzuführen ist.

**Comment by LukasCBossert** [comment]
Ja, mir kam das auch komisch vor, dass bei diesem Lexikon der Verlag genannt wird - nehme ich wieder raus.

**Comment by LukasCBossert** [comment]
erledigt
