### ISSUE TITLE
Drei oder mehr Verlagsstädte führen zu "u.a."?

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#20]
Im Leitfaden taucht öfters eine Stadt plus "u.a." auf. Aber auch jeweils: "New Haven/London" und "Oxford/New York". (Letzteres hatte ich als "Oxford, NY" fehlinterpretiert.)
Vielleicht riecht das doch nach einer Regel:
 - bei zwei Städten: 1. Stadt / 2. Stadt
 - bei drei oder mehr Städten: gib 1. Stadt plus "u.a." aus (statt jetzt 1. Stadt / 2. Stadt / 3. Stadt etc.)

**Comment by LukasCBossert** [comment]
ja, ich meine irgendwo die Regel auch gelesen zu haben. 
aber mich hat es eher stutzig gemacht, dass Städte mit `u. a.` abgekürzt werden und autoren/Herausgeber mit `et al.` ?!

**Comment by AlfonsoMuskedunder** [comment]
Ich würde fast vorschlagen: In den Fällen, in denen der Leitfaden nicht explizit eine Regel ausspricht und Widersprüche produziert, halten wir uns an allgemein akzeptierte Praktiken?

**Comment by LukasCBossert** [comment]
ja, wichtig(er) ist dann die Einheitlichkeit.
