### ISSUE TITLE
Zitationen sollten mit Punkt enden.

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#22]
Im Leitfaden enden die Zitationen mit einem Punkt.

Die Bibliographie im LF sieht allerdings keine Punkte vor. Ist das wieder ein Fall von Uneinheitlichkeit? Falls ja, wäre es aus unserer Sicht vorzuziehen, auch die Bibliographieeinträge zu punktieren.

**Comment by LukasCBossert** [comment]
Du meinst mit Zitationen das Erscheinen in der Fußnote? Das ist dann richtig, dass dort ein Punkt ist, weil jede Fußnote mit einem Punkt an sich endet.

Möchte man in der Bibliographie dann doch einen Punkt am Ende haben, kann man den mit der Präambel-Option `enddot` aktivieren (habe ich flux eingebaut).

**Comment by AlfonsoMuskedunder** [comment]
Thanks. Aber manche Fußnoten zeigen jetzt einen Punkt, andere nicht?

(Mir fehlt manchmal noch das Vokabular: wie nennt man denn die Zitatfußnote? Und noch wichtiger: Wie nennt man die eigentlich in TeX-speak? Ich hab ja bislang immer von der Kurzform/short form gesprochen...)

**Comment by LukasCBossert** [comment]
Dass manche Fußnoten in der Bsp-Datei einen Punkt haben und andere nicht, liegt daran, dass `\footcite` automatisch einen Punkt erzeugt, verwendet man `\footnote{\cite{}}` muss man den Schlusspunkt manuell setzen. 

Zitatfußnote, oder Kurzform oder Label, das andere bezeichne ich dann immer als Vollzitat.

**Comment by AlfonsoMuskedunder** [comment]
Joah. Klingt plausibel. 😂
