### ISSUE TITLE
Sortierung bei 'shorttitle'

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#27]
Zotero befüllt oftmals das Feld 'shorttitle'. Dieses wiederum sticht 'author' bei der Sortierung aus.

Um Zotero-Nutzern - davon gibt es womöglich viele? - das Leben zu erleichtern, wäre ein Fix eine coole Sache.

**Comment by LukasCBossert** [comment]
sollte gelöst sein, jetzt wird nur `sortshorttitle` berücksichtigt.

**Comment by AlfonsoMuskedunder** [comment]
Komisch, irgendwie hat die eine Zeile die Sortierung scheinbar komplett zerschossen...

**Comment by AlfonsoMuskedunder** [comment]
Es gibt einen kleinen Kollateralschaden: Wir hatten bei den Lexika zur Sortierung einen `shorttitle` angegeben; der wird jetzt natürlich auch ignoriert.

Wollen wir für Lexika einfach ein anderes Feld bestücken, etwa auch `shorthand` (wie bei `source`s)? (Welchen Grund hat es überhaupt, dass wir für `source` und `@catalog` zwei verschiedene Felder benutzt haben?)
Oder zurück zum alten status quo und die doofen Zotero-`shorttitle`s löschen?
