### ISSUE TITLE
Issues zu "hier S."

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#30]
Im Groben funktioniert das feature.

Eine Anpassung wäre noch wichtig: In den Fällen, in denen tatsächlich "hier S." angefügt wird, wird das Kürzel "S." (im Falle von `endpages`) vor den Seitenangaben des Bibliographieeintrags in der Kurzzitation kassiert.
- First best-Lösung: "S." anführen, je nachdem ob `endpages` angegeben ist
- Second best: "S." unconditionally anführen - vielleicht einfacher zu implementieren, und die Wahrscheinlichkeit, dass `firstcitefull`-user auch `endpages` angeben wollen, ist hoch, denke ich.

Zuletzt wäre es vielleicht auch eleganter, das feature in die Option `firstcitefull` zu integrieren? Wenn ich es richtig verstehe, würde ja `\AtEveryCitekey{\global\togglefalse{cbx:citepages}}` gecheckt, selbst wenn `firstcitefull` nicht geladen würde, oder?

**Comment by AlfonsoMuskedunder** [comment]
Nachtrag: das "S." wird nicht nur in den betreffenden Kurzzitationen gekillt, sondern auch in allen Einträgen mit Seitenangaben in der Bibliografie.

**Comment by LukasCBossert** [comment]
abhängig von der Option `endpages`: Dann soll ggf. zweimal "S." stehen - bei der Erstzitation für die Seitenrange und die "hier S."-Angabe; zudem dann in der Bibliographie? 

Wenn `endpages` nicht aktiviert ist, soll dann "hier S." oder "hier " heißen?

**Comment by AlfonsoMuskedunder** [comment]
Frage 1: Genau so!

Frage 2: Nicht "hier S.", sondern nur "hier". (Wäre konsistent mit der sonstigen Zitations- und Bibliografierweise.)

**Comment by LukasCBossert** [comment]
verstehe.

**Comment by AlfonsoMuskedunder** [comment]
Ich habe mal am Code herumgespielt; mit
```
\DeclareFieldFormat{pages}{%
  \bibstring{pages} #1%
  \ifboolexpr{ test {\ifcitation} and not test {\ifblank{#1}} }
    {\global\toggletrue{cbx:citepages}}
    {}}
```
statt
```
\DeclareFieldFormat{pages}{%
  #1%
  ...
```
wird "S." gedruckt.

**Comment by AlfonsoMuskedunder** [comment]
Bzw.
```
\DeclareFieldFormat{pages}{%
  \ifbool{bbx:endpages}
    {\mkpageprefix[bookpagination]{#1}}
    {#1}%
  \ifboolexpr{ test {\ifcitation} and not test {\ifblank{#1}} }
    {\global\toggletrue{cbx:citepages}}
    {}}
```
in die arthistory.bbx. Es funktioniert sogar abhängig von `endpages=true/false`. 

Allerdings ist der Abstand zwischen Fußnote 14 und 15 in unserem Testdokument seltsam groß...

**Comment by LukasCBossert** [comment]
Mir scheint, dass

```
\renewbibmacro*{postnote}{%
  \iffieldundef{postnote}
    {}
    {\ifboolexpr{bool {cbx:firstcitefull} and not test {\ifciteseen}}
       {\setunit{\addcomma\addspace}%
        \bibstring{thiscite}%
        \setunit{\addspace}}
       {\setunit{\postnotedelim}}%
     \printfield{postnote}}}
```

ausreicht - aber `\ifboolexpr{bool {cbx:firstcitefull} and not test {\ifciteseen}}`klappt noch nicht und ich weiß noch nicht warum.

**Comment by LukasCBossert** [comment]
ich denke, dass man gar nichts am Seiten-Makro ändern muss? denn das wird ja über die `endpages`-Option gesteuert.
