### ISSUE TITLE
Mehrere Erscheinungsjahre nicht ganz stimmig

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#33]
Siehe die Einträge `Eimer1970` und `Eimer1970a` in der `examples.bib`.

Bei `date = {1970/1971}` ist die Ausgabe in der Kurzzitation "korrekt" (gemäß Leitfaden) `1970--1971`. Allerdings fehlt das zweite Jahr im bib-Eintrag.

Bei `year = {1970/1971}` ist die Ausgabe `1970/1971` sowohl in der Kurz- wie in der Langzitation, und es wird die Warnung ausgegeben `year field '1970/1971' in entry 'Eimer1970' is not an integer - this will probably not sort properly.` Die Frage ist, ob man einfach darauf achten sollte, in analogen Fällen `date` statt `year` zu definieren, oder sollen date und year eigentlich schon eine ähnliche Funktion erfüllen?

**Comment by LukasCBossert** [comment]
Wie du schreibst, man muss leider darauf achten, dass die ›Spezialfälle‹ nur ins Feld `date` kommen. `year` kann damit nicht umgehen. 
Ich denke, es sollte reichen, wenn man das in der Dokumentation vermerkt.
