### ISSUE TITLE
Unglücklich: Bei Herausgeberschrift wird im Literaturverzeichnis Vorname zuerst genannt

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#34]
Siehe z.B. `Satzinger2004` in der Testdatei.

Dies ist wohl ein Artefakt der Bestimmungen zu Artikeln _aus_ Herausgeberschriften (bei denen die Herausgeber des Sammelbandes zuerst mit Vornamen genannt werden sollen), aber wenn eine solche Schrift als ganzes bibliografiert wird, führt das zu einer krassen Inkonsistenz in der Bibliografie.

Da würde ich pragmatischer Weise eigentlich lieber einen Bruch mit dem Leitfaden riskieren, und auch bei Herausgebern pauschal nach Nachnamen, Vornamen vorgehen. (So hatte es auch H.'s Doktorvater in seiner Diss. oder Habil., wie wir gesehen haben.)

Die cherry on top wäre natürlich, wenn man danach differenzieren könnte, ob Herausgeberschriften
-  als solche und Ganzes gelistet werden (dann Nach-, Vorname) oder 
-  im Zusammenhang mit einem Artikel aus dem Band (dann Vor- u. Nachname)

-- aber die cherry hätte für mich persönlich eine geringere Priorität als der fix zu "hier S." :grimacing:

**Comment by LukasCBossert** [comment]
Man könnte eine Option einbauen, die regelt, ob man stets `Nachname, Vorname` hat oder (wie im Leitfaden) je nach Eintragstyp `Nachname, Vorname` und für Hrsg `Vorname Nachname`. Dann kann jeder immer entscheiden, wie man es haben möchte.

**Comment by AlfonsoMuskedunder** [comment]
Klingt vernünftig!

Der Fall, dass einer Herausgeberschrift als Ganzes bibliografiert werden muss, wird im Leitfaden einfach gar nicht behandelt.

Ich vermute, dass die Überlegung war: Wann auch immer ein Autor/Editor an erster Stelle genannt wird -> Nachname, Vorname;
wenn Editoren später genannt werden, der besseren Lesbarkeit halber Vor- & Nachname.

Aber dann müsste man konsistenter Weise auch bspw. bei mehreren Autoren nur den ersten mit Nach-, Vorname listen und die Koautoren sofort mit Vor- % Nachnamen.

**Comment by LukasCBossert** [comment]
> Aber dann müsste man konsistenter Weise auch bspw. bei mehreren Autoren nur den ersten mit Nach-, Vorname listen und die Koautoren sofort mit Vor- % Nachnamen.

Manche Stile machen das so sogar.


Habe nur das auf Seite 52 (5. Aufl) gefunden:
![bildschirmfoto 2016-11-11 um 11 38 42](https://cloud.githubusercontent.com/assets/12896078/20212442/73d8f6ba-a803-11e6-819e-da55568a5529.png)

**Comment by AlfonsoMuskedunder** [comment]
Schau an, habe ich übersehen. Es ist auf jeden Fall nicht konsistent, finde ich.

Auf S. 50 ist mal ein Beitrag mit mehreren Autoren genannt (Giese/Lutz...), da werden auf jeden Fall alle Autoren zunächst mit Nachnamen gelistet.
