### ISSUE TITLE
Wenn hyperref geladen ist, wird für fast jede Zitation eine Warnung ausgegeben

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#35]
Wenn `hyperref` geladen ist (und nur dann), wird für die meisten Zitationen im log file eine Warnung ausgegeben. Dies bläht bei einem großen Dokument das log file unnötig auf.

Für ein Beispiel siehe https://github.com/LukasCBossert/biblatex-arthistory/blob/master/mwe_zitationen_doppelt.tex

Wenn mit pdfLaTeX kompiliert wird, erscheint bspw.: `pdfTeX warning (ext4): destination with the same identifier (name{cite.0:Satzinger2004}) has been already used, duplicate ignored`

Mit XeLaTeX: `xdvipdfmx:warning: Object @cite.0:Satzinger2004 already defined.` (Achtung: Erscheint nicht im üblichen log file.)

**Auffällig: Bei allen Zitationen, für die im MWE keine Warnung ausgegeben wird, ist ein `shorthand` definiert!**

**Comment by LukasCBossert** [comment]
Die Lösung vorgeschlagen auf http://tex.stackexchange.com/a/18927/98739 hat leider nicht funktioniert. Hast du eine Idee @moewew ?

**Comment by moewew** [comment]
Gibt es irgendeinen Grund für `\printtext[bibhypertarget]` in `cite:various`? Wenn ich das rauswerfe gibt es keine Warnungen mehr. Eigentlich müsst ihr die Links nur setzen, wenn ihr später darauf zurückkommen wollt, das geht aber eigentlich nur sinnvoll in `verbose`-like Stilen in Fußnoten.

**Comment by AlfonsoMuskedunder** [comment]
Danke @moewew!

Deine Frage kann nur @LukasCBossert beantworten. Von mir nur ein kurzer Hinweis, ohne zu wissen, ob relevant: Eigentlich erfolgen die Zitationen im Stil tatsächlich in Fußnoten (anders als im ursprünglichen MWE). Außerdem soll die allererste Zitation wahlweise den vollen bib entry ausgeben, über die Option `firstcitefull`, was vielleicht etwas in Richtung `verbose` geht?  (Allerdings sind es nicht diese "first full cites", die das Problem verursachen).

**Comment by LukasCBossert** [comment]
Aha! Vielen Dank @moewew . Das muss ich mit `\printtext[bibhyperref]` verwechselt haben, was ich will. Für den Stil `biblatex-arthistory` muss man nicht mehr auf einen Bibliographie-Eintrag (in der Fußnote) zurückkommen (soweit ich das sehe). 
Mit dem kommenden commit sollte es gelöst sein. Danke!
