### ISSUE TITLE
Jahresangaben sollen bei Zeitschriftenartikeln in Klammern gesetzt werden

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#36]
Siehe z.B. Leitfaden Seite 55.

Soll: `Schlegel, Ursula: Ein Terracottamodell des Bartolomeo Ammannati, in: Paragone/Arte 43, Nr. 503 (1992), 25–30`
Ist: `Schlegel, Ursula: Ein Terracottamodell des Bartolomeo Ammannati, in: Paragona/Arte 43, Nr. 503 1992, 25–30`

Vgl. `Schlegel1992` in der `arthistory-examples.bib`.

**Comment by LukasCBossert** [comment]
Also nur das Jahr in Klammer setzten?
Ist dies ein Sonderfall oder für alle Zeitschriften?
