### ISSUE TITLE
Feature request: Neuer type = phdthesispartial

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory#37]
Es gibt immer wieder Veröffentlichungen, die teilweise (und eben nicht ganz) der jeweiligen Diss. des Verfassers entsprechen.

Für "reine" Diss.-Veröffentlichungen durch einen Verlag existiert bislang `type = {phdthesis}` mit dem `bib string` `zugl.`. Das tolle ist, dass die Infos zur Diss ggf. in dieselbe Klammer gesetzt werden wie jene zu einer etwaigen `series`.

Exakt dasselbe feature wäre toll für "teilweise" Diss.-Veröffentlichungen. Also identisch, bis auf
`type = phdthesispartial`
`bib string` `teilw. zugl.` statt `zugl.`

**Comment by LukasCBossert** [comment]
ist schon drin.
Vgl.

```
@Book{Bonnet2001,
  author      = {Bonnet, Anne-Marie},
  title       = {\enquote{Akt} bei Dürer},
  location    = {Köln},
  year        = {2001},
  series      = {Atlas},
  number      = {4},
  dissdate    = {1992},
  disstype    = {tzugl},
  institution = {München, Ludwig-Maximilians-Univ.},
  type        = {habil},
}
```
