### ISSUE TITLE
@exhibcatalog (Ausstellungskatalog)

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-arthistory#5]
Für Ausstellungs- und Bestandskataloge.

Standardmäßig wird ein Ausstellungskatalog angenommen; Bestandskatalog wird über eine `option` angesteuert.

**Comment by AlfonsoMuskedunder** [comment]
Da fällt mir übrigens noch etwas ein: Streng genommen gibt die 4. Auflage des Leitfadens vor, dass man bei Katalogen (beider Art) unterscheiden soll zwischen solchen mit Herausgebern und solchen mit _Verfassern_. Die 5. Auflage lässt diese Unterscheidung unter den Tisch fallen, vielleicht weil man sie für überflüssig erachtet hat...?

**Comment by LukasCBossert** [comment]
Mir scheint, dass mit *Verfasser*  der Autor (`author`) und mit *Herausgeber* `editor`, zumindest lese ich das so in der 4. Auflage (Seite 27), wo nur zwischen Verf. und Hrsg. unterschieden wird.

**Comment by AlfonsoMuskedunder** [comment]
Ja, genau. Auf S. 39 der 4. Auflage wird im Kontext der Kataloge darauf eingegangen.

**Comment by LukasCBossert** [comment]
5. Aufl. Seite 52 scheint das aber auch noch drin zu haben:

![bildschirmfoto 2016-10-04 um 14 34 28](https://cloud.githubusercontent.com/assets/12896078/19074264/b3e165c6-8a3f-11e6-9b66-e9b8bc30e997.png)

**Comment by LukasCBossert** [comment]
s. https://github.com/LukasCBossert/biblatex-arthistory/blob/394f039357371b27ec9cef7f639b55d5b9925299/arthistory-test.pdf Es wird nun richtig ausgegeben.
