### ISSUE TITLE
Quellen

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-arthistory#7]
Wird über `option={source}` angesteuert und entsprechend in der Fußnote modifiziert.

**Comment by AlfonsoMuskedunder** [comment]
Auch hier sollen ja die Einträge nach der Kurzform sortiert werden. In unserer aktuellen Beispielbib müsste z.B. Horaz auf Helas folgen. Ich frage wegen https://github.com/LukasCBossert/biblatex-arthistory/issues/15

**Comment by LukasCBossert** [comment]
Gut, das wird machbar sein, da man die `shorthand` leicht(er) integrieren kann.
